veusz: change source to pypi
BioArchLinux/Packages pull request #178
Opened 2023-08-16 15:34 UTC by Kiri2002

## Involved packages

 - veusz

## Involved issue

change source to pipi from github for elegant and easy to auto-update

## Details

- [x] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [ ] Provide New Package
- [x] Fix the Packages
  - [x] PKGBUILD
  - [x] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

## Additional Note

2023-08-16 15:38 UTC, Kiri2002 commented
@starsareintherose

2023-08-17 04:33 UTC, hubutui commented
not sure why you wanna change source to pypi. you could also check github release or tag for auto-update.

2023-08-17 04:38 UTC, hubutui commented
```yaml
pre_build_script: |
  update_pkgver_and_pkgrel(_G.newver.lstrip('veusz-'))
- source: github
  github: veusz/veusz
  use_latest_release: true
```
should work.

2023-08-17 07:29 UTC, Kiri2002 commented
> not sure why you wanna change source to pypi. you could also check github release or tag for auto-update.

Because I think the pypi usually more regular in form. So when one soft both in pypi and github, i will chose pypi.

2023-08-17 08:14 UTC, starsareintherose commented on BioArchLinux/veusz/lilac.yaml
check it by yourslef

2023-08-17 14:30 UTC, starsareintherose requested changes
Follow all suggestions or it should be closed in three days

2023-08-17 17:47 UTC, Kiri2002 commented
> Follow all suggestions or it should be closed in three days

Which? Source in github/pypi or the 'syntax' in lilac?
for source, i believe pypi better, if i was wrong, please show me reason

for syntax, I don't where wrong, it just same as others in repo, and you don't want to tell me

2023-08-18 03:27 UTC, closed without merging