bio-tbtools: add pkg
BioArchLinux/Packages pull request #216
Opened 2024-07-16 09:43 UTC by Kiri2002

## Involved packages

 - Packages_Name

## Involved issue

Close #

## Details

- [ ] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [ ] Provide New Package
- [ ] Fix the Packages
  - [ ] PKGBUILD
  - [ ] lilac.yaml
  - [ ] lilac.py
- [ ] Would like to continue to work with us

## Additional Note

2024-07-16 09:45 UTC, Kiri2002 commented
@starsareintherose after this merged, the old pkg tbtools should be removed by admin

2024-07-16 23:46 UTC, starsareintherose requested changes

2024-07-16 23:46 UTC, starsareintherose commented on BioArchLinux/bio-tbtools/LICENSE
Should be deleted

2024-07-19 04:04 UTC, starsareintherose commented
You are now member, should have ability to rm some folder

2024-07-19 09:04 UTC, merged

2024-07-19 10:26 UTC, starsareintherose commented
You are not allowed to merge

2024-07-20 05:55 UTC, Kiri2002 commented
> You are not allowed to merge

sorry, i mis-understant

2024-07-20 08:05 UTC, starsareintherose commented
Please re-commit pkg

2024-07-20 08:05 UTC, starsareintherose commented
Directly

2024-07-26 11:59 UTC, Kiri2002 commented
Re-committed the pkg directly at here:
https://github.com/BioArchLinux/Packages/commit/cf9e2fa0a044aca987cebd254d6e76f39b89257d